export const cities = [
  // Estonia
  { city: "Tallinn", country: "Estonia" },
  { city: "Tartu", country: "Estonia" },
  { city: "Narva", country: "Estonia" },
  { city: "Pärnu", country: "Estonia" },
  { city: "Kohtla-Järve", country: "Estonia" },
  { city: "Viljandi", country: "Estonia" },
  { city: "Rakvere", country: "Estonia" },
  { city: "Maardu", country: "Estonia" },
  { city: "Sillamäe", country: "Estonia" },
  { city: "Kuressaare", country: "Estonia" },
  { city: "Võru", country: "Estonia" },
  { city: "Valga", country: "Estonia" },
  { city: "Haapsalu", country: "Estonia" },
  { city: "Jõhvi", country: "Estonia" },
  { city: "Keila", country: "Estonia" },
  { city: "Paide", country: "Estonia" },
  { city: "Türi", country: "Estonia" },
  { city: "Tapa", country: "Estonia" },
  { city: "Elva", country: "Estonia" },
  { city: "Põltsamaa", country: "Estonia" },
  { city: "Rapla", country: "Estonia" },
  { city: "Saue", country: "Estonia" },
  { city: "Kiviõli", country: "Estonia" },
  { city: "Põlva", country: "Estonia" },
  { city: "Jõgeva", country: "Estonia" },
  { city: "Tõrva", country: "Estonia" },
  { city: "Otepää", country: "Estonia" },
  { city: "Paldiski", country: "Estonia" },
  { city: "Kunda", country: "Estonia" },
  { city: "Mustvee", country: "Estonia" },
  { city: "Räpina", country: "Estonia" },
  { city: "Abja-Paluoja", country: "Estonia" },
  { city: "Karksi-Nuia", country: "Estonia" },
  { city: "Antsla", country: "Estonia" },
  { city: "Kilingi-Nõmme", country: "Estonia" },
  { city: "Kärdla", country: "Estonia" },
  { city: "Suure-Jaani", country: "Estonia" },
  { city: "Lihula", country: "Estonia" },
  { city: "Kallaste", country: "Estonia" },
  { city: "Tamsalu", country: "Estonia" },
  { city: "Loksa", country: "Estonia" },
  { city: "Narva-Jõesuu", country: "Estonia" },
  { city: "Vändra", country: "Estonia" },
  { city: "Mõisaküla", country: "Estonia" },
  { city: "Püssi", country: "Estonia" },
  { city: "Võhma", country: "Estonia" },
  { city: "Sindi", country: "Estonia" },

  // Latvia
  { city: "Rīga", country: "Latvia" },
  { city: "Daugavpils", country: "Latvia" },
  { city: "Liepāja", country: "Latvia" },
  { city: "Jelgava", country: "Latvia" },
  { city: "Jūrmala", country: "Latvia" },
  { city: "Ventspils", country: "Latvia" },
  { city: "Rēzekne", country: "Latvia" },
  { city: "Valmiera", country: "Latvia" },
  { city: "Jēkabpils", country: "Latvia" },
  { city: "Ogre", country: "Latvia" },
  { city: "Tukums", country: "Latvia" },
  { city: "Cēsis", country: "Latvia" },
  { city: "Salaspils", country: "Latvia" },
  { city: "Kuldīga", country: "Latvia" },
  { city: "Olaine", country: "Latvia" },
  { city: "Saldus", country: "Latvia" },
  { city: "Talsi", country: "Latvia" },
  { city: "Dobele", country: "Latvia" },
  { city: "Krāslava", country: "Latvia" },
  { city: "Līvāni", country: "Latvia" },
  { city: "Gulbene", country: "Latvia" },
  { city: "Alūksne", country: "Latvia" },
  { city: "Aizkraukle", country: "Latvia" },
  { city: "Madona", country: "Latvia" },
  { city: "Sigulda", country: "Latvia" },
  { city: "Bauska", country: "Latvia" },
  { city: "Ludza", country: "Latvia" },
  { city: "Preiļi", country: "Latvia" },
  { city: "Balvi", country: "Latvia" },
  { city: "Limbaži", country: "Latvia" },
  { city: "Valka", country: "Latvia" },
  { city: "Smiltene", country: "Latvia" },
  { city: "Auce", country: "Latvia" },
  { city: "Aizpute", country: "Latvia" },
  { city: "Grobiņa", country: "Latvia" },
  { city: "Ainaži", country: "Latvia" },
  { city: "Baldone", country: "Latvia" },
  { city: "Cesvaine", country: "Latvia" },
  { city: "Dagda", country: "Latvia" },
  { city: "Durbe", country: "Latvia" },
  { city: "Iecava", country: "Latvia" },
  { city: "Jaunjelgava", country: "Latvia" },
  { city: "Kandava", country: "Latvia" },
  { city: "Kārsava", country: "Latvia" },
  { city: "Lielvārde", country: "Latvia" },
  { city: "Mazsalaca", country: "Latvia" },
  { city: "Priekule", country: "Latvia" },
  { city: "Rūjiena", country: "Latvia" },
  { city: "Sabile", country: "Latvia" },
  { city: "Viļāni", country: "Latvia" },

  // Lithuania
  { city: "Vilnius", country: "Lithuania" },
  { city: "Kaunas", country: "Lithuania" },
  { city: "Klaipėda", country: "Lithuania" },
  { city: "Šiauliai", country: "Lithuania" },
  { city: "Panevėžys", country: "Lithuania" },
  { city: "Alytus", country: "Lithuania" },
  { city: "Marijampolė", country: "Lithuania" },
  { city: "Mažeikiai", country: "Lithuania" },
  { city: "Jonava", country: "Lithuania" },
  { city: "Utena", country: "Lithuania" },
  { city: "Kėdainiai", country: "Lithuania" },
  { city: "Telšiai", country: "Lithuania" },
  { city: "Tauragė", country: "Lithuania" },
  { city: "Ukmergė", country: "Lithuania" },
  { city: "Visaginas", country: "Lithuania" },
  { city: "Plungė", country: "Lithuania" },
  { city: "Kretinga", country: "Lithuania" },
  { city: "Šilutė", country: "Lithuania" },
  { city: "Palanga", country: "Lithuania" },
  { city: "Radviliškis", country: "Lithuania" },
  { city: "Gargždai", country: "Lithuania" },
  { city: "Rokiškis", country: "Lithuania" },
  { city: "Druskininkai", country: "Lithuania" },
  { city: "Elektrėnai", country: "Lithuania" },
  { city: "Vilkaviškis", country: "Lithuania" },
  { city: "Biržai", country: "Lithuania" },
  { city: "Kuršėnai", country: "Lithuania" },
  { city: "Jurbarkas", country: "Lithuania" },
  { city: "Garliava", country: "Lithuania" },
  { city: "Vievis", country: "Lithuania" },
  { city: "Anykščiai", country: "Lithuania" },
  { city: "Varėna", country: "Lithuania" },
  { city: "Kaišiadorys", country: "Lithuania" },
  { city: "Prienai", country: "Lithuania" },
  { city: "Naujoji Akmenė", country: "Lithuania" },
  { city: "Raseiniai", country: "Lithuania" },
  { city: "Trakai", country: "Lithuania" },
  { city: "Joniškis", country: "Lithuania" },
  { city: "Zarasai", country: "Lithuania" },
  { city: "Kupiškis", country: "Lithuania" },
  { city: "Pasvalys", country: "Lithuania" },
  { city: "Šalčininkai", country: "Lithuania" },
  { city: "Švenčionys", country: "Lithuania" },
  { city: "Molėtai", country: "Lithuania" },
  { city: "Ignalina", country: "Lithuania" },
  { city: "Skuodas", country: "Lithuania" },
  { city: "Pabradė", country: "Lithuania" },
  { city: "Grigiškės", country: "Lithuania" },
  { city: "Kelmė", country: "Lithuania" },
  { city: "Nida", country: "Lithuania" },

  // Finland
  { city: "Helsinki", country: "Finland" },
  { city: "Espoo", country: "Finland" },
  { city: "Tampere", country: "Finland" },
  { city: "Vantaa", country: "Finland" },
  { city: "Oulu", country: "Finland" },
  { city: "Turku", country: "Finland" },
  { city: "Jyväskylä", country: "Finland" },
  { city: "Lahti", country: "Finland" },
  { city: "Kuopio", country: "Finland" },
  { city: "Pori", country: "Finland" },
  { city: "Kouvola", country: "Finland" },
  { city: "Joensuu", country: "Finland" },
  { city: "Lappeenranta", country: "Finland" },
  { city: "Hämeenlinna", country: "Finland" },
  { city: "Vaasa", country: "Finland" },
  { city: "Seinäjoki", country: "Finland" },
  { city: "Rovaniemi", country: "Finland" },
  { city: "Mikkeli", country: "Finland" },
  { city: "Kotka", country: "Finland" },
  { city: "Salo", country: "Finland" },
  { city: "Porvoo", country: "Finland" },
  { city: "Kokkola", country: "Finland" },
  { city: "Hyvinkää", country: "Finland" },
  { city: "Lohja", country: "Finland" },
  { city: "Järvenpää", country: "Finland" },
  { city: "Rauma", country: "Finland" },
  { city: "Kajaani", country: "Finland" },
  { city: "Kirkkonummi", country: "Finland" },
  { city: "Tuusula", country: "Finland" },
  { city: "Vihti", country: "Finland" },
  { city: "Nurmijärvi", country: "Finland" },
  { city: "Kerava", country: "Finland" },
  { city: "Savonlinna", country: "Finland" },
  { city: "Imatra", country: "Finland" },
  { city: "Riihimäki", country: "Finland" },
  { city: "Nokia", country: "Finland" },
  { city: "Kuusamo", country: "Finland" },
  { city: "Raisio", country: "Finland" },
  { city: "Naantali", country: "Finland" },
  { city: "Varkaus", country: "Finland" },
  { city: "Iisalmi", country: "Finland" },
  { city: "Valkeakoski", country: "Finland" },
  { city: "Ylöjärvi", country: "Finland" },
  { city: "Äänekoski", country: "Finland" },
  { city: "Loviisa", country: "Finland" },
  { city: "Hämeenkyrö", country: "Finland" },
  { city: "Sastamala", country: "Finland" },
  { city: "Kauhava", country: "Finland" },
  { city: "Kurikka", country: "Finland" },
  { city: "Uusikaupunki", country: "Finland" },
  { city: "Kemi", country: "Finland" },

  // Norway
  { city: "Oslo", country: "Norway" },
  { city: "Bergen", country: "Norway" },
  { city: "Trondheim", country: "Norway" },
  { city: "Stavanger", country: "Norway" },
  { city: "Bærum", country: "Norway" },
  { city: "Kristiansand", country: "Norway" },
  { city: "Fredrikstad", country: "Norway" },
  { city: "Tromsø", country: "Norway" },
  { city: "Drammen", country: "Norway" },
  { city: "Sandnes", country: "Norway" },
  { city: "Sarpsborg", country: "Norway" },
  { city: "Ålesund", country: "Norway" },
  { city: "Skien", country: "Norway" },
  { city: "Sandefjord", country: "Norway" },
  { city: "Haugesund", country: "Norway" },
  { city: "Tønsberg", country: "Norway" },
  { city: "Moss", country: "Norway" },
  { city: "Porsgrunn", country: "Norway" },
  { city: "Bodø", country: "Norway" },
  { city: "Arendal", country: "Norway" },
  { city: "Hamar", country: "Norway" },
  { city: "Larvik", country: "Norway" },
  { city: "Halden", country: "Norway" },
  { city: "Lillehammer", country: "Norway" },
  { city: "Molde", country: "Norway" },
  { city: "Harstad", country: "Norway" },
  { city: "Kongsberg", country: "Norway" },
  { city: "Gjøvik", country: "Norway" },
  { city: "Steinkjer", country: "Norway" },
  { city: "Askøy", country: "Norway" },
  { city: "Askim", country: "Norway" },
  { city: "Elverum", country: "Norway" },
  { city: "Narvik", country: "Norway" },
  { city: "Kristiansund", country: "Norway" },
  { city: "Horten", country: "Norway" },
  { city: "Mo i Rana", country: "Norway" },
  { city: "Alta", country: "Norway" },
  { city: "Leirvik", country: "Norway" },
  { city: "Grimstad", country: "Norway" },
  { city: "Levanger", country: "Norway" },
  { city: "Førde", country: "Norway" },
  { city: "Notodden", country: "Norway" },
  { city: "Egersund", country: "Norway" },
  { city: "Florø", country: "Norway" },
  { city: "Voss", country: "Norway" },
  { city: "Lillestrøm", country: "Norway" },
  { city: "Jessheim", country: "Norway" },
  { city: "Ski", country: "Norway" },
  { city: "Kongsvinger", country: "Norway" },
  { city: "Bryne", country: "Norway" },

  // Sweden
  { city: "Stockholm", country: "Sweden" },
  { city: "Göteborg (Gothenburg)", country: "Sweden" },
  { city: "Malmö", country: "Sweden" },
  { city: "Uppsala", country: "Sweden" },
  { city: "Linköping", country: "Sweden" },
  { city: "Örebro", country: "Sweden" },
  { city: "Västerås", country: "Sweden" },
  { city: "Helsingborg", country: "Sweden" },
  { city: "Norrköping", country: "Sweden" },
  { city: "Umeå", country: "Sweden" },
  { city: "Jönköping", country: "Sweden" },
  { city: "Lund", country: "Sweden" },
  { city: "Gävle", country: "Sweden" },
  { city: "Sundsvall", country: "Sweden" },
  { city: "Södertälje", country: "Sweden" },
  { city: "Borås", country: "Sweden" },
  { city: "Eskilstuna", country: "Sweden" },
  { city: "Karlstad", country: "Sweden" },
  { city: "Halmstad", country: "Sweden" },
  { city: "Växjö", country: "Sweden" },
  { city: "Karlskrona", country: "Sweden" },
  { city: "Kalmar", country: "Sweden" },
  { city: "Skövde", country: "Sweden" },
  { city: "Östersund", country: "Sweden" },
  { city: "Falun", country: "Sweden" },
  { city: "Trollhättan", country: "Sweden" },
  { city: "Örnsköldsvik", country: "Sweden" },
  { city: "Kristianstad", country: "Sweden" },
  { city: "Nyköping", country: "Sweden" },
  { city: "Skellefteå", country: "Sweden" },
  { city: "Karlskoga", country: "Sweden" },
  { city: "Piteå", country: "Sweden" },
  { city: "Motala", country: "Sweden" },
  { city: "Landskrona", country: "Sweden" },
  { city: "Uddevalla", country: "Sweden" },
  { city: "Lidköping", country: "Sweden" },
  { city: "Sandviken", country: "Sweden" },
  { city: "Katrineholm", country: "Sweden" },
  { city: "Enköping", country: "Sweden" },
  { city: "Varberg", country: "Sweden" },
  { city: "Falkenberg", country: "Sweden" },
  { city: "Ängelholm", country: "Sweden" },
  { city: "Trelleborg", country: "Sweden" },
  { city: "Alingsås", country: "Sweden" },
  { city: "Vänersborg", country: "Sweden" },
  { city: "Härnösand", country: "Sweden" },
  { city: "Boden", country: "Sweden" },
  { city: "Luleå", country: "Sweden" },
  { city: "Kiruna", country: "Sweden" },
  { city: "Mariestad", country: "Sweden" },

  // United Kingdom
  { city: "London", country: "UK" },
  { city: "Birmingham", country: "UK" },
  { city: "Manchester", country: "UK" },
  { city: "Glasgow", country: "UK" },
  { city: "Liverpool", country: "UK" },
  { city: "Leeds", country: "UK" },
  { city: "Edinburgh", country: "UK" },
  { city: "Bristol", country: "UK" },
  { city: "Sheffield", country: "UK" },
  { city: "Cardiff", country: "UK" },
  { city: "Belfast", country: "UK" },
  { city: "Newcastle upon Tyne", country: "UK" },
  { city: "Leicester", country: "UK" },
  { city: "Nottingham", country: "UK" },
  { city: "Southampton", country: "UK" },
  { city: "Portsmouth", country: "UK" },
  { city: "Bradford", country: "UK" },
  { city: "Coventry", country: "UK" },
  { city: "Kingston upon Hull", country: "UK" },
  { city: "Stoke-on-Trent", country: "UK" },
  { city: "Wolverhampton", country: "UK" },
  { city: "Plymouth", country: "UK" },
  { city: "Derby", country: "UK" },
  { city: "Swansea", country: "UK" },
  { city: "Aberdeen", country: "UK" },
  { city: "Reading", country: "UK" },
  { city: "Oxford", country: "UK" },
  { city: "Cambridge", country: "UK" },
  { city: "York", country: "UK" },
  { city: "Preston", country: "UK" },
  { city: "Sunderland", country: "UK" },
  { city: "Norwich", country: "UK" },
  { city: "Exeter", country: "UK" },
  { city: "Ipswich", country: "UK" },
  { city: "Gloucester", country: "UK" },
  { city: "Blackpool", country: "UK" },
  { city: "Middlesbrough", country: "UK" },
  { city: "Bolton", country: "UK" },
  { city: "Bournemouth", country: "UK" },
  { city: "Peterborough", country: "UK" },
  { city: "Luton", country: "UK" },
  { city: "Milton Keynes", country: "UK" },
  { city: "Dundee", country: "UK" },
  { city: "Inverness", country: "UK" },
  { city: "Bath", country: "UK" },
  { city: "Chester", country: "UK" },
  { city: "Canterbury", country: "UK" },
  { city: "Lincoln", country: "UK" },
  { city: "Worcester", country: "UK" },
  { city: "Salisbury", country: "UK" },
  { city: "Brighton", country: "UK" },
  { city: "Southend-on-Sea", country: "UK" },
  { city: "Warrington", country: "UK" },
  { city: "Rotherham", country: "UK" },
  { city: "Northampton", country: "UK" },
  { city: "Swindon", country: "UK" },

  // Germany
  { city: "Berlin", country: "Germany" },
  { city: "Hamburg", country: "Germany" },
  { city: "München (Munich)", country: "Germany" },
  { city: "Köln (Cologne)", country: "Germany" },
  { city: "Frankfurt am Main", country: "Germany" },
  { city: "Stuttgart", country: "Germany" },
  { city: "Düsseldorf", country: "Germany" },
  { city: "Leipzig", country: "Germany" },
  { city: "Dortmund", country: "Germany" },
  { city: "Essen", country: "Germany" },
  { city: "Bremen", country: "Germany" },
  { city: "Dresden", country: "Germany" },
  { city: "Hannover", country: "Germany" },
  { city: "Nürnberg (Nuremberg)", country: "Germany" },
  { city: "Duisburg", country: "Germany" },
  { city: "Bochum", country: "Germany" },
  { city: "Wuppertal", country: "Germany" },
  { city: "Bielefeld", country: "Germany" },
  { city: "Bonn", country: "Germany" },
  { city: "Münster", country: "Germany" },
  { city: "Mannheim", country: "Germany" },
  { city: "Karlsruhe", country: "Germany" },
  { city: "Augsburg", country: "Germany" },
  { city: "Wiesbaden", country: "Germany" },
  { city: "Mönchengladbach", country: "Germany" },
  { city: "Gelsenkirchen", country: "Germany" },
  { city: "Braunschweig", country: "Germany" },
  { city: "Chemnitz", country: "Germany" },
  { city: "Kiel", country: "Germany" },
  { city: "Aachen", country: "Germany" },
  { city: "Halle (Saale)", country: "Germany" },
  { city: "Magdeburg", country: "Germany" },
  { city: "Freiburg im Breisgau", country: "Germany" },
  { city: "Krefeld", country: "Germany" },
  { city: "Lübeck", country: "Germany" },
  { city: "Oberhausen", country: "Germany" },
  { city: "Erfurt", country: "Germany" },
  { city: "Mainz", country: "Germany" },
  { city: "Rostock", country: "Germany" },
  { city: "Kassel", country: "Germany" },
  { city: "Hagen", country: "Germany" },
  { city: "Hamm", country: "Germany" },
  { city: "Saarbrücken", country: "Germany" },
  { city: "Mülheim an der Ruhr", country: "Germany" },
  { city: "Potsdam", country: "Germany" },
  { city: "Ludwigshafen am Rhein", country: "Germany" },
  { city: "Oldenburg", country: "Germany" },
  { city: "Leverkusen", country: "Germany" },
  { city: "Osnabrück", country: "Germany" },
  { city: "Solingen", country: "Germany" },
  { city: "Heidelberg", country: "Germany" },

  // Spain
  { city: "Madrid", country: "Spain" },
  { city: "Barcelona", country: "Spain" },
  { city: "Valencia", country: "Spain" },
  { city: "Sevilla (Seville)", country: "Spain" },
  { city: "Zaragoza (Saragossa)", country: "Spain" },
  { city: "Málaga", country: "Spain" },
  { city: "Murcia", country: "Spain" },
  { city: "Palma", country: "Spain" },
  { city: "Las Palmas de Gran Canaria", country: "Spain" },
  { city: "Bilbao", country: "Spain" },
  { city: "Alicante", country: "Spain" },
  { city: "Córdoba", country: "Spain" },
  { city: "Valladolid", country: "Spain" },
  { city: "Vigo", country: "Spain" },
  { city: "Gijón", country: "Spain" },
  { city: "L'Hospitalet de Llobregat", country: "Spain" },
  { city: "A Coruña (Corunna)", country: "Spain" },
  { city: "Vitoria-Gasteiz", country: "Spain" },
  { city: "Granada", country: "Spain" },
  { city: "Elche", country: "Spain" },
  { city: "Oviedo", country: "Spain" },
  { city: "Santa Cruz de Tenerife", country: "Spain" },
  { city: "Badalona", country: "Spain" },
  { city: "Cartagena", country: "Spain" },
  { city: "Terrassa", country: "Spain" },
  { city: "Jerez de la Frontera", country: "Spain" },
  { city: "Sabadell", country: "Spain" },
  { city: "Móstoles", country: "Spain" },
  { city: "Alcalá de Henares", country: "Spain" },
  { city: "Pamplona", country: "Spain" },
  { city: "Fuenlabrada", country: "Spain" },
  { city: "Almería", country: "Spain" },
  { city: "Leganés", country: "Spain" },
  { city: "San Sebastián", country: "Spain" },
  { city: "Santander", country: "Spain" },
  { city: "Castellón de la Plana", country: "Spain" },
  { city: "Burgos", country: "Spain" },
  { city: "Albacete", country: "Spain" },
  { city: "Getafe", country: "Spain" },
  { city: "Alcorcón", country: "Spain" },
  { city: "Salamanca", country: "Spain" },
  { city: "Logroño", country: "Spain" },
  { city: "Huelva", country: "Spain" },
  { city: "Badajoz", country: "Spain" },
  { city: "San Cristóbal de La Laguna", country: "Spain" },
  { city: "Marbella", country: "Spain" },
  { city: "Lleida", country: "Spain" },
  { city: "Tarragona", country: "Spain" },
  { city: "León", country: "Spain" },
  { city: "Cádiz", country: "Spain" },
  { city: "Girona", country: "Spain" },

  // France
  { city: "Paris", country: "France" },
  { city: "Marseille", country: "France" },
  { city: "Lyon", country: "France" },
  { city: "Toulouse", country: "France" },
  { city: "Nice", country: "France" },
  { city: "Nantes", country: "France" },
  { city: "Strasbourg", country: "France" },
  { city: "Montpellier", country: "France" },
  { city: "Bordeaux", country: "France" },
  { city: "Lille", country: "France" },
  { city: "Rennes", country: "France" },
  { city: "Reims", country: "France" },
  { city: "Le Havre", country: "France" },
  { city: "Saint-Étienne", country: "France" },
  { city: "Toulon", country: "France" },
  { city: "Grenoble", country: "France" },
  { city: "Dijon", country: "France" },
  { city: "Angers", country: "France" },
  { city: "Nîmes", country: "France" },
  { city: "Villeurbanne", country: "France" },
  { city: "Le Mans", country: "France" },
  { city: "Aix-en-Provence", country: "France" },
  { city: "Clermont-Ferrand", country: "France" },
  { city: "Brest", country: "France" },
  { city: "Tours", country: "France" },
  { city: "Limoges", country: "France" },
  { city: "Amiens", country: "France" },
  { city: "Annecy", country: "France" },
  { city: "Perpignan", country: "France" },
  { city: "Besançon", country: "France" },
  { city: "Orléans", country: "France" },
  { city: "Metz", country: "France" },
  { city: "Rouen", country: "France" },
  { city: "Mulhouse", country: "France" },
  { city: "Caen", country: "France" },
  { city: "Boulogne-Billancourt", country: "France" },
  { city: "Nancy", country: "France" },
  { city: "Argenteuil", country: "France" },
  { city: "Saint-Denis", country: "France" },
  { city: "Roubaix", country: "France" },
  { city: "Tourcoing", country: "France" },
  { city: "Avignon", country: "France" },
  { city: "Créteil", country: "France" },
  { city: "Poitiers", country: "France" },
  { city: "Versailles", country: "France" },
  { city: "Pau", country: "France" },
  { city: "Colmar", country: "France" },
  { city: "La Rochelle", country: "France" },
  { city: "Cannes", country: "France" },
  { city: "Antibes", country: "France" },
  { city: "Béziers", country: "France" },

  // Poland
  { city: "Warszawa (Warsaw)", country: "Poland" },
  { city: "Kraków (Cracow)", country: "Poland" },
  { city: "Łódź", country: "Poland" },
  { city: "Wrocław", country: "Poland" },
  { city: "Poznań", country: "Poland" },
  { city: "Gdańsk", country: "Poland" },
  { city: "Szczecin", country: "Poland" },
  { city: "Bydgoszcz", country: "Poland" },
  { city: "Lublin", country: "Poland" },
  { city: "Katowice", country: "Poland" },
  { city: "Białystok", country: "Poland" },
  { city: "Gdynia", country: "Poland" },
  { city: "Częstochowa", country: "Poland" },
  { city: "Radom", country: "Poland" },
  { city: "Sosnowiec", country: "Poland" },
  { city: "Toruń", country: "Poland" },
  { city: "Kielce", country: "Poland" },
  { city: "Rzeszów", country: "Poland" },
  { city: "Gliwice", country: "Poland" },
  { city: "Zabrze", country: "Poland" },
  { city: "Olsztyn", country: "Poland" },
  { city: "Bielsko-Biała", country: "Poland" },
  { city: "Bytom", country: "Poland" },
  { city: "Zielona Góra", country: "Poland" },
  { city: "Rybnik", country: "Poland" },
  { city: "Ruda Śląska", country: "Poland" },
  { city: "Opole", country: "Poland" },
  { city: "Tychy", country: "Poland" },
  { city: "Gorzów Wielkopolski", country: "Poland" },
  { city: "Dąbrowa Górnicza", country: "Poland" },
  { city: "Elbląg", country: "Poland" },
  { city: "Płock", country: "Poland" },
  { city: "Wałbrzych", country: "Poland" },
  { city: "Włocławek", country: "Poland" },
  { city: "Tarnów", country: "Poland" },
  { city: "Chorzów", country: "Poland" },
  { city: "Koszalin", country: "Poland" },
  { city: "Kalisz", country: "Poland" },
  { city: "Legnica", country: "Poland" },
  { city: "Grudziądz", country: "Poland" },
  { city: "Słupsk", country: "Poland" },
  { city: "Jaworzno", country: "Poland" },
  { city: "Jastrzębie-Zdrój", country: "Poland" },
  { city: "Nowy Sącz", country: "Poland" },
  { city: "Jelenia Góra", country: "Poland" },
  { city: "Siedlce", country: "Poland" },
  { city: "Mysłowice", country: "Poland" },
  { city: "Konin", country: "Poland" },
  { city: "Piotrków Trybunalski", country: "Poland" },
  { city: "Inowrocław", country: "Poland" },

  // Italy
  { city: "Roma (Rome)", country: "Italy" },
  { city: "Milano (Milan)", country: "Italy" },
  { city: "Napoli (Naples)", country: "Italy" },
  { city: "Torino (Turin)", country: "Italy" },
  { city: "Palermo", country: "Italy" },
  { city: "Genova (Genoa)", country: "Italy" },
  { city: "Bologna", country: "Italy" },
  { city: "Firenze (Florence)", country: "Italy" },
  { city: "Bari", country: "Italy" },
  { city: "Venezia (Venice)", country: "Italy" },
  { city: "Verona", country: "Italy" },
  { city: "Catania", country: "Italy" },
  { city: "Padova (Padua)", country: "Italy" },
  { city: "Trieste", country: "Italy" },
  { city: "Brescia", country: "Italy" },
  { city: "Taranto", country: "Italy" },
  { city: "Prato", country: "Italy" },
  { city: "Parma", country: "Italy" },
  { city: "Reggio Calabria", country: "Italy" },
  { city: "Modena", country: "Italy" },
  { city: "Reggio Emilia", country: "Italy" },
  { city: "Perugia", country: "Italy" },
  { city: "Livorno", country: "Italy" },
  { city: "Ravenna", country: "Italy" },
  { city: "Cagliari", country: "Italy" },
  { city: "Foggia", country: "Italy" },
  { city: "Rimini", country: "Italy" },
  { city: "Salerno", country: "Italy" },
  { city: "Ferrara", country: "Italy" },
  { city: "Sassari", country: "Italy" },
  { city: "Latina", country: "Italy" },
  { city: "Giugliano in Campania", country: "Italy" },
  { city: "Monza", country: "Italy" },
  { city: "Siracusa", country: "Italy" },
  { city: "Pescara", country: "Italy" },
  { city: "Bergamo", country: "Italy" },
  { city: "Forlì", country: "Italy" },
  { city: "Trento", country: "Italy" },
  { city: "Vicenza", country: "Italy" },
  { city: "Terni", country: "Italy" },
  { city: "Bolzano", country: "Italy" },
  { city: "Novara", country: "Italy" },
  { city: "Piacenza", country: "Italy" },
  { city: "Ancona", country: "Italy" },
  { city: "Andria", country: "Italy" },
  { city: "Arezzo", country: "Italy" },
  { city: "Udine", country: "Italy" },
  { city: "Cesena", country: "Italy" },
  { city: "Lecce", country: "Italy" },
  { city: "Pesaro", country: "Italy" },
  { city: "Alessandria", country: "Italy" },

  // Portugal
  { city: "Lisboa (Lisbon)", country: "Portugal" },
  { city: "Porto", country: "Portugal" },
  { city: "Vila Nova de Gaia", country: "Portugal" },
  { city: "Amadora", country: "Portugal" },
  { city: "Braga", country: "Portugal" },
  { city: "Coimbra", country: "Portugal" },
  { city: "Funchal", country: "Portugal" },
  { city: "Setúbal", country: "Portugal" },
  { city: "Faro", country: "Portugal" },
  { city: "Almada", country: "Portugal" },
  { city: "Agualva-Cacém", country: "Portugal" },
  { city: "Queluz", country: "Portugal" },
  { city: "Aveiro", country: "Portugal" },
  { city: "Guimarães", country: "Portugal" },
  { city: "Viseu", country: "Portugal" },
  { city: "Leiria", country: "Portugal" },
  { city: "Barreiro", country: "Portugal" },
  { city: "Évora", country: "Portugal" },
  { city: "Portimão", country: "Portugal" },
  { city: "Vila Franca de Xira", country: "Portugal" },
  { city: "Odivelas", country: "Portugal" },
  { city: "Barcelos", country: "Portugal" },
  { city: "Castelo Branco", country: "Portugal" },
  { city: "Santarém", country: "Portugal" },
  { city: "Póvoa de Varzim", country: "Portugal" },
  { city: "Matosinhos", country: "Portugal" },
  { city: "Viana do Castelo", country: "Portugal" },
  { city: "Elvas", country: "Portugal" },
  { city: "Beja", country: "Portugal" },
  { city: "Covilhã", country: "Portugal" },
  { city: "Guarda", country: "Portugal" },
  { city: "Espinho", country: "Portugal" },
  { city: "Fafe", country: "Portugal" },
  { city: "Loures", country: "Portugal" },
  { city: "Sintra", country: "Portugal" },
  { city: "Cascais", country: "Portugal" },
  { city: "Oeiras", country: "Portugal" },
  { city: "Torres Vedras", country: "Portugal" },
  { city: "Peniche", country: "Portugal" },
  { city: "Tomar", country: "Portugal" },
  { city: "Abrantes", country: "Portugal" },
  { city: "Chaves", country: "Portugal" },
  { city: "Bragança", country: "Portugal" },
  { city: "Vila Real", country: "Portugal" },
  { city: "Lagos", country: "Portugal" },
  { city: "Olhão", country: "Portugal" },
  { city: "Marinha Grande", country: "Portugal" },
  { city: "Alcobaça", country: "Portugal" },
  { city: "Estoril", country: "Portugal" },
  { city: "Ovar", country: "Portugal" },

  // Austria
  { city: "Wien (Vienna)", country: "Austria" },
  { city: "Graz", country: "Austria" },
  { city: "Linz", country: "Austria" },
  { city: "Salzburg", country: "Austria" },
  { city: "Innsbruck", country: "Austria" },
  { city: "Klagenfurt", country: "Austria" },
  { city: "Villach", country: "Austria" },
  { city: "Wels", country: "Austria" },
  { city: "Sankt Pölten", country: "Austria" },
  { city: "Dornbirn", country: "Austria" },
  { city: "Steyr", country: "Austria" },
  { city: "Wiener Neustadt", country: "Austria" },
  { city: "Feldkirch", country: "Austria" },
  { city: "Bregenz", country: "Austria" },
  { city: "Leonding", country: "Austria" },
  { city: "Klosterneuburg", country: "Austria" },
  { city: "Baden bei Wien", country: "Austria" },
  { city: "Wolfsberg", country: "Austria" },
  { city: "Leoben", country: "Austria" },
  { city: "Krems an der Donau", country: "Austria" },
  { city: "Traun", country: "Austria" },
  { city: "Amstetten", country: "Austria" },
  { city: "Lustenau", country: "Austria" },
  { city: "Kapfenberg", country: "Austria" },
  { city: "Mödling", country: "Austria" },
  { city: "Hallein", country: "Austria" },
  { city: "Kufstein", country: "Austria" },
  { city: "Traiskirchen", country: "Austria" },
  { city: "Schwechat", country: "Austria" },
  { city: "Braunau am Inn", country: "Austria" },
  { city: "Stockerau", country: "Austria" },
  { city: "Saalfelden", country: "Austria" },
  { city: "Ansfelden", country: "Austria" },
  { city: "Tulln an der Donau", country: "Austria" },
  { city: "Hohenems", country: "Austria" },
  { city: "Spittal an der Drau", country: "Austria" },
  { city: "Ternitz", country: "Austria" },
  { city: "Perchtoldsdorf", country: "Austria" },
  { city: "Bludenz", country: "Austria" },
  { city: "Telfs", country: "Austria" },
  { city: "Rankweil", country: "Austria" },
  { city: "Vöcklabruck", country: "Austria" },
  { city: "Eisenstadt", country: "Austria" },
  { city: "Bad Ischl", country: "Austria" },
  { city: "Zwettl", country: "Austria" },
  { city: "Feldkirchen in Kärnten", country: "Austria" },
  { city: "Gmunden", country: "Austria" },
  { city: "Knittelfeld", country: "Austria" },
  { city: "Judenburg", country: "Austria" },
  { city: "Waidhofen an der Ybbs", country: "Austria" },

  // Belgium
  { city: "Brussel", country: "Belgium" },
  { city: "Antwerpen", country: "Belgium" },
  { city: "Gent (Ghent)", country: "Belgium" },
  { city: "Charleroi", country: "Belgium" },
  { city: "Liège", country: "Belgium" },
  { city: "Brugge (Bruges)", country: "Belgium" },
  { city: "Namur", country: "Belgium" },
  { city: "Leuven", country: "Belgium" },
  { city: "Mons", country: "Belgium" },
  { city: "Aalst", country: "Belgium" },
  { city: "Mechelen", country: "Belgium" },
  { city: "La Louvière", country: "Belgium" },
  { city: "Kortrijk", country: "Belgium" },
  { city: "Hasselt", country: "Belgium" },
  { city: "Sint-Niklaas", country: "Belgium" },
  { city: "Oostende", country: "Belgium" },
  { city: "Tournai", country: "Belgium" },
  { city: "Genk", country: "Belgium" },
  { city: "Seraing", country: "Belgium" },
  { city: "Roeselare", country: "Belgium" },
  { city: "Verviers", country: "Belgium" },
  { city: "Mouscron", country: "Belgium" },
  { city: "Beveren", country: "Belgium" },
  { city: "Dendermonde", country: "Belgium" },
  { city: "Beringen", country: "Belgium" },
  { city: "Turnhout", country: "Belgium" },
  { city: "Dilbeek", country: "Belgium" },
  { city: "Vilvoorde", country: "Belgium" },
  { city: "Herstal", country: "Belgium" },
  { city: "Ninove", country: "Belgium" },
  { city: "Waregem", country: "Belgium" },
  { city: "Deinze", country: "Belgium" },
  { city: "Lokeren", country: "Belgium" },
  { city: "Geel", country: "Belgium" },
  { city: "Sint-Truiden", country: "Belgium" },
  { city: "Ieper", country: "Belgium" },
  { city: "Wevelgem", country: "Belgium" },
  { city: "Bilzen", country: "Belgium" },
  { city: "Knokke-Heist", country: "Belgium" },
  { city: "Diest", country: "Belgium" },
  { city: "Tienen", country: "Belgium" },
  { city: "Denderleeuw", country: "Belgium" },
  { city: "Halle", country: "Belgium" },
  { city: "Zottegem", country: "Belgium" },
  { city: "Oudenaarde", country: "Belgium" },
  { city: "Menen", country: "Belgium" },
  { city: "Braine-l'Alleud", country: "Belgium" },
  { city: "Waterloo", country: "Belgium" },
  { city: "Wavre", country: "Belgium" },
  { city: "Tubize", country: "Belgium" },
  { city: "Nivelles", country: "Belgium" },

  // Netherlands
  { city: "Amsterdam", country: "Netherlands" },
  { city: "Rotterdam", country: "Netherlands" },
  { city: "Den Haag (The Hague)", country: "Netherlands" },
  { city: "Utrecht", country: "Netherlands" },
  { city: "Eindhoven", country: "Netherlands" },
  { city: "Groningen", country: "Netherlands" },
  { city: "Tilburg", country: "Netherlands" },
  { city: "Almere", country: "Netherlands" },
  { city: "Nijmegen", country: "Netherlands" },
  { city: "Breda", country: "Netherlands" },
  { city: "Enschede", country: "Netherlands" },
  { city: "Haarlem", country: "Netherlands" },
  { city: "Arnhem", country: "Netherlands" },
  { city: "Zaanstad", country: "Netherlands" },
  { city: "Amersfoort", country: "Netherlands" },
  { city: "Apeldoorn", country: "Netherlands" },
  { city: "'s-Hertogenbosch", country: "Netherlands" },
  { city: "Hoofddorp", country: "Netherlands" },
  { city: "Maastricht", country: "Netherlands" },
  { city: "Leiden", country: "Netherlands" },
  { city: "Dordrecht", country: "Netherlands" },
  { city: "Zoetermeer", country: "Netherlands" },
  { city: "Zwolle", country: "Netherlands" },
  { city: "Deventer", country: "Netherlands" },
  { city: "Delft", country: "Netherlands" },
  { city: "Alkmaar", country: "Netherlands" },
  { city: "Leeuwarden", country: "Netherlands" },
  { city: "Venlo", country: "Netherlands" },
  { city: "Helmond", country: "Netherlands" },
  { city: "Oss", country: "Netherlands" },
  { city: "Amstelveen", country: "Netherlands" },
  { city: "Hilversum", country: "Netherlands" },
  { city: "Purmerend", country: "Netherlands" },
  { city: "Roosendaal", country: "Netherlands" },
  { city: "Schiedam", country: "Netherlands" },
  { city: "Spijkenisse", country: "Netherlands" },
  { city: "Vlaardingen", country: "Netherlands" },
  { city: "Almelo", country: "Netherlands" },
  { city: "Gouda", country: "Netherlands" },
  { city: "Emmen", country: "Netherlands" },
  { city: "Hengelo", country: "Netherlands" },
  { city: "Ede", country: "Netherlands" },
  { city: "Alphen aan den Rijn", country: "Netherlands" },
  { city: "Katwijk", country: "Netherlands" },
  { city: "Nieuwegein", country: "Netherlands" },
  { city: "Barneveld", country: "Netherlands" },
  { city: "Hoorn", country: "Netherlands" },
  { city: "Middelburg", country: "Netherlands" },
  { city: "Assen", country: "Netherlands" },
  { city: "Veenendaal", country: "Netherlands" },
  { city: "Capelle aan den IJssel", country: "Netherlands" },

  // Denmark
  { city: "København (Copenhagen)", country: "Denmark" },
  { city: "Aarhus", country: "Denmark" },
  { city: "Odense", country: "Denmark" },
  { city: "Aalborg", country: "Denmark" },
  { city: "Esbjerg", country: "Denmark" },
  { city: "Randers", country: "Denmark" },
  { city: "Kolding", country: "Denmark" },
  { city: "Horsens", country: "Denmark" },
  { city: "Vejle", country: "Denmark" },
  { city: "Roskilde", country: "Denmark" },
  { city: "Herning", country: "Denmark" },
  { city: "Silkeborg", country: "Denmark" },
  { city: "Næstved", country: "Denmark" },
  { city: "Fredericia", country: "Denmark" },
  { city: "Viborg", country: "Denmark" },
  { city: "Køge", country: "Denmark" },
  { city: "Holstebro", country: "Denmark" },
  { city: "Taastrup", country: "Denmark" },
  { city: "Slagelse", country: "Denmark" },
  { city: "Hillerød", country: "Denmark" },
  { city: "Sønderborg", country: "Denmark" },
  { city: "Svendborg", country: "Denmark" },
  { city: "Hjørring", country: "Denmark" },
  { city: "Holbæk", country: "Denmark" },
  { city: "Frederikshavn", country: "Denmark" },
  { city: "Nørresundby", country: "Denmark" },
  { city: "Ringsted", country: "Denmark" },
  { city: "Skive", country: "Denmark" },
  { city: "Haderslev", country: "Denmark" },
  { city: "Birkerød", country: "Denmark" },
  { city: "Rødovre", country: "Denmark" },
  { city: "Ballerup", country: "Denmark" },
  { city: "Ikast", country: "Denmark" },
  { city: "Middelfart", country: "Denmark" },
  { city: "Nykøbing Falster", country: "Denmark" },
  { city: "Skanderborg", country: "Denmark" },
  { city: "Aabenraa", country: "Denmark" },
  { city: "Grenaa", country: "Denmark" },
  { city: "Frederikssund", country: "Denmark" },
  { city: "Hørsholm", country: "Denmark" },
  { city: "Nyborg", country: "Denmark" },
  { city: "Faaborg", country: "Denmark" },
  { city: "Solrød Strand", country: "Denmark" },
  { city: "Aars", country: "Denmark" },
  { city: "Struer", country: "Denmark" },
  { city: "Brønderslev", country: "Denmark" },
  { city: "Varde", country: "Denmark" },
  { city: "Kalundborg", country: "Denmark" },
  { city: "Nykøbing Mors", country: "Denmark" },
  { city: "Otterup", country: "Denmark" },
]