export const artistListingsData = [
    {
        id: 1,
        city: "Riga, Latvia",
        dateRange: "5 - 12 September 2026"
    },
    {
        id: 2,
        city: "Tallin, Estonia",
        dateRange: "21 - 28 October 2026"
    },
    {
        id: 3,
        city: "Berlin, Germany",
        dateRange: "1 - 7 November 2026"
    },
    {
        id: 4,
        city: "Vilnius, Lithuania",
        dateRange: "20 - 24 December 2026"
    },
    {
        id: 5,
        city: "Warsaw, Poland",
        dateRange: "12 - 16 January 2027"
    }
]

export const lithuanianCities = [
  "Vilnius",
  "Kaunas",
  "Klaipėda",
  "Šiauliai",
  "Panevėžys",
  "Alytus",
  "Marijampolė",
  "Mažeikiai",
  "Jonava",
  "Utena",
  "Kėdainiai",
  "Telšiai",
  "Visaginas",
  "Tauragė",
  "Ukmergė",
  "Plungė",
  "Šilutė",
  "Kretinga",
  "Palanga",
  "Radviliškis",
  "Druskininkai",
  "Rokiškis",
  "Biržai",
  "Kuršėnai",
  "Elektrėnai",
  "Jurbarkas",
  "Garliava",
  "Vilkaviškis",
  "Gargždai",
  "Raseiniai",
  "Naujoji Akmenė",
  "Joniškis",
  "Anykščiai",
  "Lentvaris",
  "Grigiškės",
  "Varėna",
  "Kelmė",
  "Pasvalys",
  "Zarasai",
  "Kaišiadorys",
  "Šalčininkai",
  "Šakiai",
  "Švenčionys",
  "Skuodas",
  "Kupiškis",
  "Vievis",
  "Ignalina",
  "Pabradė",
  "Kazlų Rūda",
  "Nemenčinė",
  "Rietavas",
  "Birštonas",
  "Šeduva",
  "Žiežmariai",
  "Šilalė",
  "Pakruojis",
  "Akmenė",
  "Molėtai",
  "Lazdijai",
  "Prienai",
  "Eišiškės",
  "Šventoji",
  "Veisiejai",
  "Pagėgiai",
  "Dūkštas"
]